### ISSUE TITLE
[STORY] Setup movie database

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#1]
## Description

Setup the movie database.

### Tasks

- [x] Design schema
  - [x] Movie table for sample movies
  - [x] Vote table
  - [x] Result table
  - [x] Room table
  - [x] Participant table
  - [x] Audit log table
- [x] Create migration
- [x] Create DB seed script
- [x] Add useful DB commands
