### ISSUE TITLE
[STORY] Create Timer Component

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#11]
## Description

Create a timer component.

### Tasks

- [x] Create a timer component which displays a countdown
- [x] The timer is green in the first third, yellow in the second third, and red in the third third
- [x] The timer has a shimmer animation which runs every 5 seconds with [Framer Motion](https://www.framer.com/motion/)
- [x] Unit tests

### Related links

- [Timer comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=1%3A270&t=6A8DPSvSORAVwrpJ-1)
