### ISSUE TITLE
[STORY] Create Card Component

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#12]
## Description

Create movie card component.

### Tasks

- [x] Card comp
- [x] Rating comp
- [x] User Score comp
- [x] Card data should be fed to the card as props
- [x] Card has hover effects using [Framer Motion](https://www.framer.com/motion/)

### Related links

- [Card comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=26%3A164&t=6A8DPSvSORAVwrpJ-1)
- [Rating comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=10%3A39&t=6A8DPSvSORAVwrpJ-1)
- [User Score comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=10%3A54&t=6A8DPSvSORAVwrpJ-1)
