### ISSUE TITLE
[RESEARCH] QR Codes

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#13]
## Description

Answer the questions about QR codes.

### Tasks

- [ ] Create implementation stories

### Questions

- [ ] How can we generate QR codes per room?
- [ ] Any libraries that help with this?

### Notes

- Preferably no paid services ❌
