### ISSUE TITLE
[RESEARCH] Web Sockets

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#14]
## Description

Research web socket implementations.

### Tasks

- [x] Create stories on how to add web sockets
- [x] Answer questions

### Questions

- [x] What are web sockets?
- [x] Any libraries to help establish web socket connections?
- [x] How can apps with web sockets be deployed on [Vercel](https://vercel.com/)?
