### ISSUE TITLE
[RESEARCH] Randomly Generated Room Codes

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#15]
## Description

Research how to generate room codes.

### Tasks

- [ ] Create stories for randomly generating room codes
- [ ] Answer questions

### Questions

- [ ] What is a reasonable length for a room code? 6 digits? 4 digits?
- [ ] Any libraries to help manage this?

Relates to #14
