### ISSUE TITLE
[RESEARCH] Scanning QR Codes from Phone

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#16]
## Description

Research how to scan QR codes from phones using the web browser

### Tasks

- [ ] Create stories to implement QR code phone scanning
- [ ] Answer questions

### Questions

- [ ] Do browsers support QR code scanning out of the box?
- [ ] Any libraries to help?

Relates to #13
