### ISSUE TITLE
[RESEARCH] Google Auth

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#18]
## Description

Research adding Google Auth with NextAuth.

### Tasks

- [ ] Create stories to implement Google Auth
- [ ] Answer questions

### Questions

- [ ] What do we need to add Google Auth?
- [ ] Does [NextAuth](https://next-auth.js.org/) offer a provider?
- [ ] What new environment variables do we need?
- [ ] Any other auth providers we can add?
