### ISSUE TITLE
[STORY] Create TurboRepo monorepo

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#24]
## Description

Create a TurboRepo monorepo to house the services required to run Movie Night.

### Tasks

- [ ] Update to using [pnpm](https://pnpm.io/) as a Node package manager.
- [ ] Follow this guide [here](https://turbo.build/repo/docs/getting-started/existing-monorepo).

#### Update README
- [ ] App description
- [ ] Project structure
- [ ] How to run?
- [ ] How to test?
- [ ] Where to find?

Here's a basic [example](https://github.com/vercel/turbo/tree/main/examples/basic).
