### ISSUE TITLE
[STORY] Create Initial Fastify Server

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#25]
## Description

Create an initial Fastify server with a basic Web Socket implementation.

### Tasks
- [x] Create a Fastify web socket app named `web-sockets` under the `apps/` directory.
- [x] Follow the setup guide [here](https://www.fastify.io/).
- [x] Add `trpc` and Web Sockets [here](https://trpc.io/docs/server/adapters/fastify#how-to-enable-subscriptions-websocket).

Here's an [example](https://github.com/trpc/trpc/tree/main/examples/fastify-server).

relates to #24
