### ISSUE TITLE
[STORY] Update README

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#27]
## Description

Update README to give more information on Movie Night.

### Tasks

- [ ] App description
- [ ] Project structure
- [ ] How to run?
- [ ] How to test?
- [ ] Where to find?
