### ISSUE TITLE
[STORY] Add Storybook for Component Development

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#28]
## Description

Add [Storybook](https://storybook.js.org/) for better component development.

### Tasks

- [x] Add a Storybook app named `workshop` under the `apps/` directory.
- [x] Follow this [guide](https://storybook.js.org/docs/react/get-started/install/).
- [x] Write stories for existing components.
- [x] Customize Storybook app look and feel.
- [x] Deploy Storybook app to Github Pages. https://github.com/marketplace/actions/deploy-storybook-to-github-pages

relates to #24
