### ISSUE TITLE
[STORY] Create Sign on Page

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#31]
## Description

Create the sign on page.

### Tasks

- [ ] Create a page at the path of `/`.
- [ ] Present the user with a "Continue with Discord" option.
- [ ] Present the user with a "Continue as guest" option.
- [ ] After successfully logging in or as a guest, move to a new page named `/lobby/create` using the `next/router` package.

### Related Links

* [Figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=12%3A201&mode=design&t=ypjaoBcqy6ydZN78-1)
* [Pages and layouts](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#index-routes)
* [next/router](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#injecting-the-router)
