### ISSUE TITLE
[STORY] Create Lobby Creation Page

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#32]
## Description

Create the lobby creation page.

### Tasks
- [ ] Create a new page at `/lobby/create`.
- [ ] The "Host" button will route to the `/lobby/host` page using the `next/router` package.
- [ ] The "Join" button will route to the `/lobby/join` page using the `next/router` package.

### Related Links

- [Figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=1%3A57&mode=design&t=ypjaoBcqy6ydZN78-1)
- [next/router](https://nextjs.org/docs/pages/building-your-application/routing/linking-and-navigating#injecting-the-router)
