### ISSUE TITLE
[STORY] Create Lobby Host Page

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#33]
## Description

Create the lobby host page.

### Tasks
- [ ] Create a new page at `/lobby/host`.
- [ ] Upon page load, initialize a web socket connection.
- [ ] Upon web socket connection, create a room and generate a key.
- [ ] Display the room key.
- [ ] Subscribe to room participant updates.
- [ ] Display a list of participants.

### Related Links

- [Figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=1%3A2&mode=design&t=ypjaoBcqy6ydZN78-1)
