### ISSUE TITLE
[STORY] Create Room Socket

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#34]
## Description

Create a data stream that creates a room and sends a unique ID to the client.

### Tasks

- [ ] Create a function to generate unique ids.
- [ ] Insert record into room table.
- [ ] Send room id to client upon successful room creation.
- [ ] Send error code upon failure to create room.

### Related Links

- [Db schema](https://dbdiagram.io/d/6458827bdca9fb07c4abc7f9)
