### ISSUE TITLE
[STORY] Create Room Join Service

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#38]
## Description

Create a data stream that allows user to join a room using a unique room id.

### Tasks

- [ ] Create a function to accept unique room id.
- [ ] Search for room in room table.
- [ ] Add user to room if the room exists.
- [ ] Send error if room doesn't exist.
- [ ] Send error if session is already in progress.

### Related Links

- [Db schema](https://dbdiagram.io/d/6458827bdca9fb07c4abc7f9)
