### ISSUE TITLE
[STORY] Create Button Component

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#5]
## Description

Create a button component.

### Tasks

- [ ] Component should have flexible text
- [ ] Component should have state controlled by props. ie `disabled` is a prop based in rather than internal state
- [ ] Component should have a variant prop
- [ ] Unit tests

### Related links

- [Button comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?node-id=1-128&t=NbrpI4LDFgtSbtV4-0)

Relates to #9
