### ISSUE TITLE
[STORY] Create Input Component

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#8]
## Description

Create an input component.

### Tasks

- [x] Component should have a flexible label
- [x] Component should have state controlled by props. ie `value` is a prop which sets the value of the input element
- [x] Component should have an `onChange` prop which accepts a function to update an upper level value
- [x] Unit tests

### Related Links

- [Input comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=1-280)
