### ISSUE TITLE
[STORY] Create Link Component

### ISSUE THREAD

**Issue by aamathews23** [Unnamed-Labs/movie-night#9]
## Description

Create a link component.

### Tasks

- [ ] Component should have flexible text
- [ ] Component should have state controlled by props. ie `disabled` is a prop based rather than internal state
- [ ] Component should wrap the `Link` component provided by `next/link`
- [ ] Component should have the following variants
  - [ ] primary
  - [ ] secondary
  - [ ] standalone
  - [ ] disabled
- [ ] Unit tests

### Related links

- [Link comp figma](https://www.figma.com/file/Evwmo3caFxwjjhVVMfCbfS/Movie-Night?type=design&node-id=1%3A128&t=6A8DPSvSORAVwrpJ-1) -- same as the button and also the standalone text

Relates to #5
